### ISSUE TITLE
Error Getting File from Cloud Storage

### ISSUE THREAD

**Issue by EmmanuelX2** [adrianhajdin/ecommerce#23]
Last 10 minutes of the video, after entering the API keys from Payload inside the .env file we created in the beginning. 

ERROR (payload): Error getting file from cloud storage
    err: {
      "type": "Error",
      "message": "Missing required parameter USERNAME",     
      "stack":
          InvalidParameterException: Missing required parameter USERNAME
              at C:\Users\raven\Desktop\e-commerce-store\node_modules\amazon-cognito-identity-js\lib\Client.js:128:19   
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
      "name": "InvalidParameterException",
      "code": "InvalidParameterException"
    }

**Comment by Jose-henry** [comment]
same i have been getting this error too when I am working

[15:22:27] ERROR (payload): Error getting file from cloud storage
    err: {
      "type": "S3ServiceException",
      "message": "Access Denied",
      "stack":
          AccessDenied: Access Denied
              at throwDefaultError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22)    
              at C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39
              at de_GetObjectCommandError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:4412:20)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-flexible-checksums\dist-cjs\flexibleChecksumsMiddleware.js:63:20
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-endpoint-middleware.js:14:24
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-middleware.js:9:20        
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@payloadcms\plugin-cloud\src\staticHandler.ts:41:22
      "name": "AccessDenied",
      "$fault": "client",
      "$metadata": {
        "httpStatusCode": 403,
        "requestId": "60D8QXCB8QNHY5RJ",
        "extendedRequestId": "1v/6XYjB83/PzPccHM8iKt39Io8oNpf/8j+xsE6SLrVKBuG/Ba77e+Dz6hWGTXLWsufpn8X81pudeE25rqB6izbm12pkA0kD",
        "attempts": 1,
        "totalRetryDelay": 0
      },
      "Code": "AccessDenied",
      "RequestId": "60D8QXCB8QNHY5RJ",
      "HostId": "1v/6XYjB83/PzPccHM8iKt39Io8oNpf/8j+xsE6SLrVKBuG/Ba77e+Dz6hWGTXLWsufpn8X81pudeE25rqB6izbm12pkA0kD"
    }
[15:22:27] ERROR (payload): Error getting file from cloud storage
    err: {
      "type": "S3ServiceException",
      "message": "Access Denied",
      "stack":
          AccessDenied: Access Denied
              at throwDefaultError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22)    
              at C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39
              at de_GetObjectCommandError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:4412:20)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-flexible-checksums\dist-cjs\flexibleChecksumsMiddleware.js:63:20
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-endpoint-middleware.js:14:24
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-middleware.js:9:20        
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@payloadcms\plugin-cloud\src\staticHandler.ts:41:22
      "name": "AccessDenied",
      "$fault": "client",
      "$metadata": {
        "httpStatusCode": 403,
        "requestId": "60D3F3X4ZGH5PV7F",
        "extendedRequestId": "dMgds9m9I6ZVLolRrOLa6vCL3n85TOiBeacD26PBJwYfJlN0uk0vHKb8ZKg1PHZeU/0HGAZE1ujVYCT/YIj5FjZYr8c/biLL",
        "attempts": 1,
        "totalRetryDelay": 0
      },
      "Code": "AccessDenied",
      "RequestId": "60D3F3X4ZGH5PV7F",
      "HostId": "dMgds9m9I6ZVLolRrOLa6vCL3n85TOiBeacD26PBJwYfJlN0uk0vHKb8ZKg1PHZeU/0HGAZE1ujVYCT/YIj5FjZYr8c/biLL"
    }
[15:22:28] ERROR (payload): Error getting file from cloud storage
    err: {
      "type": "S3ServiceException",
      "message": "Access Denied",
      "stack":
          AccessDenied: Access Denied
              at throwDefaultError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22)    
              at C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39
              at de_GetObjectCommandError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:4412:20)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-flexible-checksums\dist-cjs\flexibleChecksumsMiddleware.js:63:20
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-endpoint-middleware.js:14:24
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-middleware.js:9:20        
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
              at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules\@payloadcms\plugin-cloud\src\staticHandler.ts:41:22
      "name": "AccessDenied",
      "$fault": "client",
      "$metadata": {
        "httpStatusCode": 403,
        "requestId": "DN1BVZCXMVCFBSGK",
        "extendedRequestId": "OiedUCTKwMLSwimhfqj1vDaRbla5lAan90KHpwVJYRZENLuVE8pyPK6juQXivIm0hM5mAwTH2aR35sSRLmk+z0oFVvB3ztLq",
        "attempts": 1,
        "totalRetryDelay": 0
      },
      "Code": "AccessDenied",
      "RequestId": "DN1BVZCXMVCFBSGK",
      "HostId": "OiedUCTKwMLSwimhfqj1vDaRbla5lAan90KHpwVJYRZENLuVE8pyPK6juQXivIm0hM5mAwTH2aR35sSRLmk+z0oFVvB3ztLq"
    }

**Comment by danterohlin** [comment]
> same i have been getting this error too when I am working
> 
> [15:22:27] ERROR (payload): Error getting file from cloud storage err: { "type": "S3ServiceException", "message": "Access Denied", "stack": AccessDenied: Access Denied at throwDefaultError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22) at C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39 at de_GetObjectCommandError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:4412:20) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-flexible-checksums\dist-cjs\flexibleChecksumsMiddleware.js:63:20 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-endpoint-middleware.js:14:24 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-middleware.js:9:20 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@payloadcms\plugin-cloud\src\staticHandler.ts:41:22 "name": "AccessDenied", "$fault": "client", "$metadata": { "httpStatusCode": 403, "requestId": "60D8QXCB8QNHY5RJ", "extendedRequestId": "1v/6XYjB83/PzPccHM8iKt39Io8oNpf/8j+xsE6SLrVKBuG/Ba77e+Dz6hWGTXLWsufpn8X81pudeE25rqB6izbm12pkA0kD", "attempts": 1, "totalRetryDelay": 0 }, "Code": "AccessDenied", "RequestId": "60D8QXCB8QNHY5RJ", "HostId": "1v/6XYjB83/PzPccHM8iKt39Io8oNpf/8j+xsE6SLrVKBuG/Ba77e+Dz6hWGTXLWsufpn8X81pudeE25rqB6izbm12pkA0kD" } [15:22:27] ERROR (payload): Error getting file from cloud storage err: { "type": "S3ServiceException", "message": "Access Denied", "stack": AccessDenied: Access Denied at throwDefaultError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22) at C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39 at de_GetObjectCommandError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:4412:20) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-flexible-checksums\dist-cjs\flexibleChecksumsMiddleware.js:63:20 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-endpoint-middleware.js:14:24 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-middleware.js:9:20 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@payloadcms\plugin-cloud\src\staticHandler.ts:41:22 "name": "AccessDenied", "$fault": "client", "$metadata": { "httpStatusCode": 403, "requestId": "60D3F3X4ZGH5PV7F", "extendedRequestId": "dMgds9m9I6ZVLolRrOLa6vCL3n85TOiBeacD26PBJwYfJlN0uk0vHKb8ZKg1PHZeU/0HGAZE1ujVYCT/YIj5FjZYr8c/biLL", "attempts": 1, "totalRetryDelay": 0 }, "Code": "AccessDenied", "RequestId": "60D3F3X4ZGH5PV7F", "HostId": "dMgds9m9I6ZVLolRrOLa6vCL3n85TOiBeacD26PBJwYfJlN0uk0vHKb8ZKg1PHZeU/0HGAZE1ujVYCT/YIj5FjZYr8c/biLL" } [15:22:28] ERROR (payload): Error getting file from cloud storage err: { "type": "S3ServiceException", "message": "Access Denied", "stack": AccessDenied: Access Denied at throwDefaultError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22) at C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39 at de_GetObjectCommandError (C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:4412:20) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-flexible-checksums\dist-cjs\flexibleChecksumsMiddleware.js:63:20 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-endpoint-middleware.js:14:24 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-middleware.js:9:20 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26 at async C:\Users\cherub\OneDrive\Desktop\e-commerce\node_modules@payloadcms\plugin-cloud\src\staticHandler.ts:41:22 "name": "AccessDenied", "$fault": "client", "$metadata": { "httpStatusCode": 403, "requestId": "DN1BVZCXMVCFBSGK", "extendedRequestId": "OiedUCTKwMLSwimhfqj1vDaRbla5lAan90KHpwVJYRZENLuVE8pyPK6juQXivIm0hM5mAwTH2aR35sSRLmk+z0oFVvB3ztLq", "attempts": 1, "totalRetryDelay": 0 }, "Code": "AccessDenied", "RequestId": "DN1BVZCXMVCFBSGK", "HostId": "OiedUCTKwMLSwimhfqj1vDaRbla5lAan90KHpwVJYRZENLuVE8pyPK6juQXivIm0hM5mAwTH2aR35sSRLmk+z0oFVvB3ztLq" }

Did you find a fix for this?

**Comment by appfresheners** [comment]
hi @adrianhajdin 
Do you have a solution for this issue?
Your assistant would be highly appreciated.

Kind regards
