### ISSUE TITLE
Hi, please i need help for resolving this error

### ISSUE THREAD

**Issue by Kapelo256** [adrianhajdin/ecommerce#6]
⨯ src\app\_components\Categories\index.tsx (18:28) @ map
 ⨯ TypeError: Cannot read properties of null (reading 'map')
    at Categories (./src/app/_components/Categories/index.tsx:49:38)
    at stringify (<anonymous>)
  16 | 
  17 |       <div className={classes.list}>
> 18 |                 {categories.map((category) => (
     |                            ^
  19 |                     <CategoryCard key={category.id} category={category} />
  20 |                 ))}
  21 |             </div>

**Comment by dikshyant3** [comment]
Provide the code snipped for it .from above error either the type for the categories is null or data is not loaded in your file.

**Comment by Kapelo256** [comment]
Hello Adrianhajdin/Ecommerce, i have replaced it with this:
{categories?.map((category) => (

))}, but i do not know how to make categories prop non-null.

**Comment by dikshyant3** [comment]
The categories props comes from payload-types.ts make sure everything is correct there. The usage of optional chaining might resolve the issue which is {categories?.map((category) => ())}, if it doesn't then there might be another codebase which causes the error.

**Comment by Alain369** [comment]
I have the same problem. I tried two times two repeat the whole chapter but lways :  ⨯ src/app/_components/Categories/index.tsx (17:21) @ map
 ⨯ TypeError: Cannot read properties of null (reading 'map')
    at Categories (./src/app/_components/Categories/index.tsx:49:38)
    at stringify (<anonymous>)
digest: "2181736854"
  15 |          <div className={classes.list}>
  16 | 
> 17 |          {categories.map((category) => (
     |                     ^
  18 |          <CategoryCard category={category} />   
  19 |          ))}
  20 | 
  
  At least the page will show when I add the ? like you said but this still wont give me any categories on my page

**Comment by Alain369** [comment]
So I found my mistake.  I was missing the fourth closing curley bracket in the categories .ts  in line 24. After adding it I got another error because of missing images in some category cards I created so I also added the question mark  to line 22 from the categoryCard index.tsx to make the image optional:     style={{ backgroundImage: `url(${media?.url})` }}. Of course you don't necessarily want this when the product is running but it helps building before you got all your images together.

**Comment by Loyoenock** [comment]
I was facing the same challenge and followed the steps as provide above, now I have no error but the categories and images are not showing. Someone help me

**Comment by AngieProg** [comment]
I had the same problem. I was missing the last "t" letter in height world in the categories.ts
I recommende chechking  the modified files in the category section: 
src\payload\collections\Categories.ts
src\payload\payload-types.ts
src\app\_graphql\products.ts
src\app\_graphql\categories.ts
src\app\_graphql\blocks.ts
src\app\(pages)\[slug]
src\app\_api\fetchDocs
src\app\_components\Categories

**Comment by Loyoenock** [comment]
Managed to sort it out, I had used lowercase c instead of uppercase.
Thank you
